### ISSUE TITLE
Model not found

### ISSUE THREAD

**Issue by iamharry-dev** [leminhhuy132/Human-Falling-Detect-Tracks#1]
Hai @leminhhuy132 

I am trying to donwload model from given link and i got page not found error 

Thanks

**Comment by leminhhuy132** [comment]
> Hai @leminhhuy132
> 
> I am trying to donwload model from given link and i got page not found error
> 
> Thanks

Hi, i checked the link again and looks like the author deleted it already. Luckily this project is still on my computer, you can download it [here](https://drive.google.com/file/d/18brbKPuudo6rmG3a0_jJJnW2fF1-4k5R/view?usp=drive_link)

**Comment by iamharry-dev** [comment]
@leminhhuy132 

Can you please accept request access.

thank you

**Comment by RealSuSeven** [comment]
> > Hai @leminhhuy132
> > I am trying to donwload model from given link and i got page not found error
> > Thanks
> 
> Hi, i checked the link again and looks like the author deleted it already. Luckily this project is still on my computer, you can download it [here](https://drive.google.com/file/d/18brbKPuudo6rmG3a0_jJJnW2fF1-4k5R/view?usp=drive_link)

Hi, I also want the models, and I have requested access to your Google Drive, my user name is realsevensu. Thanks!

**Comment by leminhhuy132** [comment]
New link [here](https://drive.google.com/file/d/18brbKPuudo6rmG3a0_jJJnW2fF1-4k5R/view?usp=sharing)
